export const CompaniesList = [
  // "Google",
  // "Amazon",
  // "Apple",
  // "Facebook",
  // "Tesla",
  // "Microsoft",
  // "Adobe",
  // "Uber",
  // "Code Nation",
  // "Sprinklr",
  // "Indeed",
  // "Salesforce",
  // "linkedin",
  // "ServiceNow",
  // "Cloud",
  // "Colaboration tools",
  // "OCI",
  // "Atlassian",
  // "Twilio",
  // "Walmart",
  // "Twitter",
  // "Tesco",
  // "Zoom",
  // "Target",
  // "Observe.ai",
  // "Bloomreach",
  // "Slack",
  // "Airtel X Labs",
  // "NetApp",
  // "UIPath",
  // "Nutanix",
  // "media.net",
  // "Paypal",
  // "Visa",
  // "Airbnb",
  // "Directi",
  // "Expedia",
  // "Qualcomm",
  // "Groupon",
  // "VMware",
  // "Nvidia",
  // "Medical",
  "Arista Networks",
  "Cadence Inc",
  "Palo Alto Networks",
  "Sports",
  "Crypto Currency",
  "Nike",
  "Coinbase",
  "Tower research Capital",
  "De shaw",
  "Graviton Research",
  "Goldman sachs",
  "World Quant",
  "Arcesium",
  "Intuit",
  "J P Morgan",
  "Morgan Stanley",
  "Fidelity Investments",
  "Wells fargo",
  "Druva",
  "Flipkart",
  "RazorPay",
  "Myntra",
  "Phone pe",
  "Udaan",
  "Ajio",
  "ClearTax",
  "PharmaEasy",
  "Paytm",
  "Urban Company",
  "Rupeek",
  "Meesho",
  "Jupiter Money",
  "Nurture.farm",
  "JusPay",
  "Dream 11",
  "Hotstar",
  "MPL",
  "Flock",
  "Zynga",
  "Inmobi",
  "Sharechat",
  "Swiggy",
  "Rivigo",
  "Zomato",
  "Delhivery",
  "Ola",
  "Freshworks",
  "Vogo",
  "Wooqer",
  "Dunzo",
  "Oyo",
  "Rubrik",
  "Compass inc",
  "Cohesity",
  "Tekion Corp",
  "Ride Sharing",
  "Harness",
  "Gojek",
  "Grab",
  "Impact analytics",
  "Oppo",
  "Turvo Inc.",
];
